"""add user_id to recipe_sale

Revision ID: 11c4863cc3b6
Revises: 1e0ba9b67f97
Create Date: 2024-06-29 14:02:45.200121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c4863cc3b6'
down_revision: Union[str, None] = '1e0ba9b67f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_sales', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe_sales', 'user_account', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_sales', type_='foreignkey')
    op.drop_column('recipe_sales', 'user_id')
    # ### end Alembic commands ###
