"""add 2fa to user

Revision ID: 11fe448dea68
Revises: e4396c694103
Create Date: 2024-06-24 09:21:13.852290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11fe448dea68'
down_revision: Union[str, None] = 'e4396c694103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('security_settings', sa.Integer(), nullable=True))
    op.alter_column('user_account', 'birthdate',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_foreign_key(None, 'user_account', 'security_settings', ['security_settings'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.alter_column('user_account', 'birthdate',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('user_account', 'security_settings')
    # ### end Alembic commands ###
