"""add foreign key of recipesales to recipesalesitems

Revision ID: 1e0ba9b67f97
Revises: 7d14688ee1e6
Create Date: 2024-06-28 17:10:18.223589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0ba9b67f97'
down_revision: Union[str, None] = '7d14688ee1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_sales_items', sa.Column('recipe_sales_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe_sales_items', 'recipe_sales', ['recipe_sales_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_sales_items', type_='foreignkey')
    op.drop_column('recipe_sales_items', 'recipe_sales_id')
    # ### end Alembic commands ###
