"""turning recipe_id and ingredient_id unique

Revision ID: bb3f26b4495e
Revises: 11c4863cc3b6
Create Date: 2024-07-05 14:50:05.620716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3f26b4495e'
down_revision: Union[str, None] = '11c4863cc3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('recipe_ingredient_uc', 'recipe_ingredient', ['recipe_id', 'ingredient_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_ingredient_uc', 'recipe_ingredient', type_='unique')
    # ### end Alembic commands ###
