"""add image_url field to recipe

Revision ID: cff6a68ba9eb
Revises: 3d0a59bea820
Create Date: 2024-06-23 14:50:41.148783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff6a68ba9eb'
down_revision: Union[str, None] = '3d0a59bea820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_url', sa.String(length=2400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image_url')
    # ### end Alembic commands ###
