"""create 2fa model for user

Revision ID: e4396c694103
Revises: fb2a499b7243
Create Date: 2024-06-24 09:15:23.348512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4396c694103'
down_revision: Union[str, None] = 'fb2a499b7243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('otp_configured', sa.Boolean(), nullable=True),
    sa.Column('secret', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_settings')
    # ### end Alembic commands ###
