"""add recipe_sales and recipe_sales_items

Revision ID: fedee66e9977
Revises: 1a0e11fa4012
Create Date: 2024-06-27 18:44:29.202845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedee66e9977'
down_revision: Union[str, None] = '1a0e11fa4012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_sales', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('recipe_sales', sa.Column('payment_status', sa.String(), nullable=True))
    op.drop_constraint('recipe_sales_recipe_id_fkey', 'recipe_sales', type_='foreignkey')
    op.drop_column('recipe_sales', 'quantity')
    op.drop_column('recipe_sales', 'recipe_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_sales', sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipe_sales', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipe_sales_recipe_id_fkey', 'recipe_sales', 'recipe', ['recipe_id'], ['id'])
    op.drop_column('recipe_sales', 'payment_status')
    op.drop_column('recipe_sales', 'payment_method')
    # ### end Alembic commands ###
