"""Increasing the password field size

Revision ID: 82491f9e82b0
Revises: e90206749d89
Create Date: 2024-06-15 20:17:08.601370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82491f9e82b0'
down_revision: Union[str, None] = 'e90206749d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
    # ### end Alembic commands ###
